### ISSUE TITLE
iGEM parts annotation

### ISSUE THREAD

**Issue by michael13162** [ICO2S/sbolstack-client-java#10]
Each part that came from an entry in the iGEM registry should have an annotation (url) that points back to the respective entry.

**Comment by jamesamcl** [comment]
That would be the URI of the part?

Sent from my iPhone

On Aug 24, 2016, at 16:57, Michael Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:

Each part that came from an entry in the iGEM registry should have an annotation (url) that points back to the respective entry.

##

**Comment by michael13162** [comment]
The URL of the entry on the iGEM registry webpage.

**Comment by michael13162** [comment]
For example: http://parts.igem.org/Part:BBa_R0011 for BBa_R0011.

**Comment by jamesamcl** [comment]
That should be the URI of the ComponentDefinition IIRC

Sent from my iPhone

On Aug 24, 2016, at 19:45, Michael Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:

For example: http://parts.igem.org/Part:BBa_R0011 for BBa_R0011.

##

**Comment by cjmyers** [comment]
Since not all URIs will have this property, it is a bit tricky to assume that you can click on it for more information.  It is good that it is true for the registry, but we are devising a new feature of SBOL Designer for annotations in which URI annotations can potentially be opened in a browser.  Granted some of these may not take you anywhere as they may point only to a piece of data somewhere else, it seems a bit more risky to assume that a URI for a part takes you to a webpage.  

I still think you should be using URIs of your own making in your iGEM to SBOL translator.  You should not be allowed to mint URIs in parts.igem.org space because you do not own that space.  What is to stop others to do the same?  If you do mint your own for these parts, then just following URI of the part will not get you to the iGEM registry.

Perhaps a better solution is to put this URI into the wasDerivedFrom field.  I could then see it to be okay to potentially make this field open a browser when the wasDerivedFrom URI is not found somewhere else.  This is much cleaner because you are making it clear where the part came from while not creating URIs in a space that you do not have rights to.

The only other solution I see is to get the iGEM folks to "bless" your translation and give you permission to create the "definitive" SBOL for these parts.  This sounds tricky to me though.

**Comment by cjmyers** [comment]
Done
